import PDFDocument from "pdfkit";
import { Lead } from "@/lib/db";

interface AnalysisResult {
  seo_score: number;
  audit_findings: {
    title: string;
    description: string;
    priority: "critical" | "high" | "medium" | "low";
    recommendation: string;
  }[];
  competitor_analysis: {
    competitor_name: string;
    strength: string;
    weakness: string;
    opportunity: string;
  }[];
  market_analysis: {
    total_competitors: number;
    market_saturation: "low" | "medium" | "high";
    opportunity_score: number;
  };
  review_analysis: {
    estimated_review_count: number;
    average_rating: number;
    improvement_areas: string[];
  };
  summary: string;
}

export async function generatePresentationPDF(
  lead: Lead,
  analysis: AnalysisResult
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40, bufferPages: true });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const formatDate = new Date().toLocaleDateString();

      // Title and header
      doc.fontSize(24).font("Helvetica-Bold").text("SEO Audit Report", { align: "center" });
      doc.moveDown(0.5);
      doc.fontSize(12).font("Helvetica").text(`Business: ${lead.business_name || lead.email}`);
      doc.text(`Contact: ${lead.email} | ${lead.phone || "N/A"}`);
      doc.text(`Date: ${formatDate}`);
      doc.moveDown(1);

      // Metrics
      doc.fontSize(12).font("Helvetica-Bold").text("Key Metrics", { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10).font("Helvetica");
      doc.text(`SEO Score: ${analysis.seo_score}/100`);
      doc.text(`Opportunity Score: ${analysis.market_analysis.opportunity_score}/100`);
      doc.text(`Average Rating: ${(analysis.review_analysis.average_rating || 0).toFixed(1)}/5.0`);
      doc.text(`Total Competitors: ${analysis.market_analysis.total_competitors}`);
      doc.moveDown(1);

      // Executive Summary
      doc.fontSize(12).font("Helvetica-Bold").text("Executive Summary", { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10).font("Helvetica").text(analysis.summary, { align: "left", width: 500 });
      doc.moveDown(1);

      // SEO Audit Findings
      doc.fontSize(12).font("Helvetica-Bold").text("SEO Audit Findings", { underline: true });
      doc.moveDown(0.5);
      analysis.audit_findings.forEach((finding) => {
        doc.fontSize(11).font("Helvetica-Bold").text(finding.title);
        doc.fontSize(9).font("Helvetica").text(`Priority: ${finding.priority.toUpperCase()}`);
        doc.text(finding.description, { width: 500 });
        doc.text(`Recommendation: ${finding.recommendation}`, { width: 500 });
        doc.moveDown(0.5);
      });
      doc.moveDown(1);

      // Competitive Analysis
      doc.fontSize(12).font("Helvetica-Bold").text("Competitive Analysis", { underline: true });
      doc.moveDown(0.5);
      analysis.competitor_analysis.forEach((competitor) => {
        doc.fontSize(11).font("Helvetica-Bold").text(competitor.competitor_name);
        doc.fontSize(9).font("Helvetica");
        doc.text(`Strength: ${competitor.strength}`, { width: 500 });
        doc.text(`Weakness: ${competitor.weakness}`, { width: 500 });
        doc.text(`Opportunity: ${competitor.opportunity}`, { width: 500 });
        doc.moveDown(0.3);
      });
      doc.moveDown(1);

      // Market Analysis
      doc.fontSize(12).font("Helvetica-Bold").text("Market Analysis", { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10).font("Helvetica");
      doc.text(`Market Saturation: ${analysis.market_analysis.market_saturation.toUpperCase()}`);
      doc.text(`Total Competitors: ${analysis.market_analysis.total_competitors}`);
      doc.text(`Opportunity Score: ${analysis.market_analysis.opportunity_score}/100`);
      doc.moveDown(1);

      // Review Analysis
      doc.fontSize(12).font("Helvetica-Bold").text("Review Analysis", { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10).font("Helvetica");
      doc.text(`Estimated Review Count: ${analysis.review_analysis.estimated_review_count}`);
      doc.text(`Average Rating: ${(analysis.review_analysis.average_rating || 0).toFixed(1)}/5.0`);
      doc.moveDown(0.5);
      doc.fontSize(11).font("Helvetica-Bold").text("Areas for Improvement:");
      analysis.review_analysis.improvement_areas.forEach((area) => {
        doc.fontSize(9).font("Helvetica").text(`• ${area}`);
      });
      doc.moveDown(1);

      // Footer
      doc.fontSize(8).font("Helvetica").text("This report was auto-generated by Listful SEO Audit.", {
        align: "center",
      });
      doc.text("For questions or follow-up, please contact us at hello@listful.com", { align: "center" });

      doc.end();
    } catch (error) {
      reject(new Error(`Failed to generate PDF: ${error instanceof Error ? error.message : String(error)}`));
    }
  });
}
